[versions]
agp = "8.11.2"
kotlin = "2.2.21"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
appcompat = "1.7.1"
material = "1.13.0"
activity = "1.12.1"
constraintlayout = "2.2.1"
desugar_jdk_libs = "2.1.5"
glide = "5.0.5"
hilt = "2.57.2"
imagepicker = "2.1"
nav_version = "2.9.6"
okhttp = "5.3.2"
pagingRuntimeKtx = "3.3.6"
recyclerview = "1.4.0"
retrofit = "3.0.0"
room_version = "2.8.4"
ksp_version = "2.2.10-2.0.2"
swiperefreshlayout = "1.2.0"
mapsMobile = "4.19.0-navikit"

#googleGmsGoogleServices = "4.4.4"
#firebaseMessaging = "25.0.1"
#playServicesBase = "18.9.0"
#firebaseBom = "34.6.0"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-paging-runtime-ktx = { module = "androidx.paging:paging-runtime-ktx", version.ref = "pagingRuntimeKtx" }
androidx-recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room_version" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room_version" }
androidx-room-paging = { module = "androidx.room:room-paging", version.ref = "room_version" }
androidx-swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swiperefreshlayout" }
compiler-glide = { module = "com.github.bumptech.glide:compiler", version.ref = "glide" }
converter-gson = { module = "com.squareup.retrofit2:converter-gson", version.ref = "retrofit" }
desugar_jdk_libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar_jdk_libs" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "hilt" }
imagepicker = { module = "com.github.dhaval2404:imagepicker", version.ref = "imagepicker" }
logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttp" }
androidx-activityKtx = { group = "androidx.activity", name = "activity-ktx", version.ref = "activity" }
fragment = {group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "nav_version"}
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
ui = {group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "nav_version"}
room = {group = "androidx.room", name = "room-runtime", version.ref = "room_version"}
maps-mobile = { module = "com.yandex.android:maps.mobile", version.ref = "mapsMobile" }

#firebase-messaging = { group = "com.google.firebase", name = "firebase-messaging", version.ref = "firebaseMessaging" }
#firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
#play-services-base = { module = "com.google.android.gms:play-services-base", version.ref = "playServicesBase" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-ksp = { id = "com.google.devtools.ksp", version.ref = "ksp_version" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }

#google-gms-google-services = { id = "com.google.gms.google-services", version.ref = "googleGmsGoogleServices" }

